import { useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { ChevronLeft, ChevronRight, Download, Eye, LoaderCircle, Plus, RotateCcw, Trash2, Upload } from "lucide-react";
import { toast } from "react-toastify";
import Swal from "sweetalert2";
import { useTranslation } from "react-i18next";
import { backupService } from "@/services/backup.service";
import { useBackupStatus, useBackups, useCreateBackup, useDeleteBackup, useRestoreBackup, useUploadBackup } from "@/hooks/useBackups";
import type { Backup, BackupStatus, BackupType } from "@/types/backup.type";
import { getErrorMessage, swalConfirm } from "@/utils/swal";

const formatDate = (value: string | null) => value ? new Date(value).toLocaleString("en-LK", { dateStyle: "medium", timeStyle: "short" }) : "—";
const formatSize = (bytes: number | null) => bytes == null ? "—" : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const badge: Record<BackupStatus, string> = { pending: "bg-amber-100 text-amber-800", running: "bg-blue-100 text-blue-800", completed: "bg-green-100 text-green-800", failed: "bg-red-100 text-red-800" };

const BackupTab = () => {
  const { t } = useTranslation();
  const [page, setPage] = useState(1); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [type, setType] = useState<BackupType | "">(""); const [status, setStatus] = useState<BackupStatus | "">("");
  const [trackedRestoreId, setTrackedRestoreId] = useState<number | null>(null);
  const uploadInput = useRef<HTMLInputElement>(null);
  const filters = useMemo(() => ({ page, from: from || undefined, to: to || undefined, type: type || undefined, status: status || undefined }), [page, from, to, type, status]);
  const { data, isLoading, isError } = useBackups(filters); const { data: summary } = useBackupStatus();
  const create = useCreateBackup(); const upload = useUploadBackup(); const remove = useDeleteBackup(); const restore = useRestoreBackup();
  const isRestoreInProgress = trackedRestoreId !== null;
  useEffect(() => {
    if (!trackedRestoreId) return;
    const attempt = data?.data.map((backup) => backup.restore).find((item) => item?.id === trackedRestoreId);
    if (!attempt || (attempt.status !== "completed" && attempt.status !== "failed")) return;
    toast[attempt.status === "completed" ? "success" : "error"](attempt.message ?? t(attempt.status === "completed" ? "adminPanel.backup.restoreCompleted" : "adminPanel.backup.restoreFailed"));
    setTrackedRestoreId(null);
  }, [data, t, trackedRestoreId]);
  const resetPage = () => setPage(1);
  const createBackup = async () => { if (await swalConfirm("Create Backup", "Are you sure you want to create a new backup of ARIS? The process may take several minutes.")) create.mutate(undefined, { onSuccess: () => toast.success("Backup process started successfully."), onError: (error) => toast.error(getErrorMessage(error)) }); };
  const uploadBackup = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) upload.mutate(file, { onSuccess: () => toast.success(t("adminPanel.backup.uploadSuccess")), onError: (error) => toast.error(getErrorMessage(error)) }); };
  const deleteBackup = async (backup: Backup) => { if (await swalConfirm("Delete Backup", `Delete ${backup.backup_code}? This cannot be undone.`)) remove.mutate(backup.id, { onSuccess: () => toast.success("Backup deleted."), onError: (error) => toast.error(getErrorMessage(error)) }); };
  const restoreBackup = async (backup: Backup) => {
    const result = await Swal.fire({ title: "Restore Backup", icon: "warning", html: `<p>WARNING: restoring <strong>${backup.backup_code}</strong> may overwrite current ARIS data.</p><p>Type <strong>RESTORE</strong> to continue.</p>`, input: "text", inputValidator: (value) => value === "RESTORE" ? undefined : "Type RESTORE exactly.", showCancelButton: true, confirmButtonText: "Confirm Restore", confirmButtonColor: "#dc2626" });
    if (result.isConfirmed) restore.mutate(backup.id, { onSuccess: (attempt) => { setTrackedRestoreId(attempt.id); toast.info(t("adminPanel.backup.restoreQueued")); }, onError: (error) => toast.error(getErrorMessage(error)) });
  };
  const showDetails = (backup: Backup) => Swal.fire({ title: backup.backup_code, html: `<p>Type: ${backup.type}</p><p>Status: ${backup.status}</p><p>Created: ${formatDate(backup.created_at)}</p><p>Size: ${formatSize(backup.file_size)}</p>${backup.error_message ? "<p>Processing failed. Review protected audit logs for details.</p>" : ""}` });
  const cards = [[t("adminPanel.backup.lastSuccessful"), formatDate(summary?.last_successful_backup?.completed_at ?? null)], [t("adminPanel.backup.nextScheduled"), formatDate(summary?.next_scheduled_backup ?? null)], [t("adminPanel.backup.status"), summary?.status === "attention" ? t("adminPanel.backup.attention") : t("adminPanel.backup.healthy")], [t("adminPanel.backup.total"), String(summary?.total_backups ?? 0)]];
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-gray-900 dark:text-slate-100">{t("adminPanel.backup.title")}</h2><p className="mt-1 text-sm text-gray-500 dark:text-slate-400">{t("adminPanel.backup.subtitle")}</p></div><div className="flex flex-wrap gap-2"><input ref={uploadInput} type="file" accept=".zip,application/zip" onChange={uploadBackup} className="hidden" /><button onClick={() => uploadInput.current?.click()} disabled={upload.isPending} className="inline-flex items-center gap-2 rounded-lg border border-blue-600 px-4 py-2 text-sm font-medium text-blue-700 hover:bg-blue-50 disabled:opacity-50"><Upload className="h-4 w-4" />{upload.isPending ? t("adminPanel.backup.uploading") : t("adminPanel.backup.upload")}</button><button onClick={createBackup} disabled={create.isPending} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"><Plus className="h-4 w-4" />{create.isPending ? t("adminPanel.backup.creating") : t("adminPanel.backup.create")}</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><p className="text-xs font-medium uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-base font-semibold text-gray-900 dark:text-slate-100">{value}</p></div>)}</div>
    <div className="flex flex-wrap gap-3"><input type="date" value={from} onChange={(e) => { setFrom(e.target.value); resetPage(); }} aria-label={t("adminPanel.audit.fromDate")} className="rounded-lg border border-gray-200 px-3 py-2 text-sm" /><input type="date" value={to} onChange={(e) => { setTo(e.target.value); resetPage(); }} aria-label={t("adminPanel.audit.toDate")} className="rounded-lg border border-gray-200 px-3 py-2 text-sm" /><select value={type} onChange={(e) => { setType(e.target.value as BackupType | ""); resetPage(); }} className="rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="">{t("adminPanel.backup.allTypes")}</option><option value="automatic">{t("adminPanel.backup.types.automatic")}</option><option value="manual">{t("adminPanel.backup.types.manual")}</option></select><select value={status} onChange={(e) => { setStatus(e.target.value as BackupStatus | ""); resetPage(); }} className="rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="">{t("adminPanel.backup.allStatuses")}</option>{(["pending", "running", "completed", "failed"] as BackupStatus[]).map((item) => <option key={item} value={item}>{t(`adminPanel.backup.statuses.${item}`)}</option>)}</select></div>
    <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-slate-700"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-slate-800"><tr>{["id", "type", "dateTime", "size", "status", "actions"].map((heading) => <th key={heading} className="px-4 py-3 font-semibold">{t(`adminPanel.backup.columns.${heading}`)}</th>)}</tr></thead><tbody className="divide-y divide-gray-100 dark:divide-slate-800">{isLoading && <tr><td colSpan={6} className="px-4 py-8 text-center text-gray-500"><LoaderCircle className="mr-2 inline h-4 w-4 animate-spin" />{t("adminPanel.backup.loading")}</td></tr>}{isRestoreInProgress && isError && <tr><td colSpan={6} className="px-4 py-3 text-center text-amber-700">{t("adminPanel.backup.restoreInProgress")}</td></tr>}{isError && !isRestoreInProgress && <tr><td colSpan={6} className="px-4 py-8 text-center text-red-600">{t("adminPanel.backup.loadError")}</td></tr>}{!isLoading && (!isError || isRestoreInProgress) && !data?.data.length && <tr><td colSpan={6} className="px-4 py-8 text-center text-gray-500">{t("adminPanel.backup.noBackups")}</td></tr>}{data?.data.map((backup) => <tr key={backup.id} className="text-gray-700 dark:text-slate-200"><td className="px-4 py-3 font-mono text-xs">{backup.backup_code}</td><td className="px-4 py-3 capitalize">{t(`adminPanel.backup.types.${backup.type}`)}</td><td className="px-4 py-3 whitespace-nowrap">{formatDate(backup.completed_at ?? backup.started_at ?? backup.created_at)}</td><td className="px-4 py-3">{formatSize(backup.file_size)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${badge[backup.status]}`}>{t(`adminPanel.backup.statuses.${backup.status}`)}</span></td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={() => showDetails(backup)} title={t("adminPanel.backup.viewDetails")} className="rounded p-1.5 hover:bg-gray-100"><Eye className="h-4 w-4" /></button>{backup.permissions.download && backup.status === "completed" && <button onClick={() => backupService.download(backup).catch((error) => toast.error(getErrorMessage(error)))} title={t("adminPanel.backup.download")} className="rounded p-1.5 hover:bg-gray-100"><Download className="h-4 w-4" /></button>}{backup.permissions.delete && <button onClick={() => deleteBackup(backup)} title={t("adminPanel.backup.delete")} className="rounded p-1.5 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button>}{backup.permissions.restore && backup.status === "completed" && <button onClick={() => restoreBackup(backup)} title={t("adminPanel.backup.restore")} className="rounded p-1.5 text-amber-700 hover:bg-amber-50"><RotateCcw className="h-4 w-4" /></button>}</div></td></tr>)}</tbody></table></div>
    {data?.meta && <div className="flex items-center justify-between text-sm text-gray-500"><span>{data.meta.total} backups</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((current) => current - 1)} className="rounded p-1 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Page {data.meta.current_page} of {data.meta.last_page}</span><button disabled={page >= data.meta.last_page} onClick={() => setPage((current) => current + 1)} className="rounded p-1 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div>}
  </div>;
};

export default BackupTab;
