<?php

namespace App\Enums;

enum AuditAction: string
{
    case CREATE = 'CREATE';
    case UPDATE = 'UPDATE';
    case DELETE = 'DELETE';

    case LOGIN = 'LOGIN';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';

    case SUBMIT = 'SUBMIT';

    case APPROVE = 'APPROVE';
    case REJECT = 'REJECT';
    case RETURN = 'RETURN';
    case RECOMMEND = 'RECOMMEND';

    case ASSIGN = 'ASSIGN';

    case UPLOAD = 'UPLOAD';
    case DOWNLOAD = 'DOWNLOAD';

    case PRINT = 'PRINT';
    case EXPORT = 'EXPORT';

    case RESTORE = 'RESTORE';

    case BACKUP_CREATED = 'BACKUP_CREATED';
    case BACKUP_STARTED = 'BACKUP_STARTED';
    case BACKUP_COMPLETED = 'BACKUP_COMPLETED';
    case BACKUP_FAILED = 'BACKUP_FAILED';
    case BACKUP_DOWNLOADED = 'BACKUP_DOWNLOADED';
    case BACKUP_DELETED = 'BACKUP_DELETED';
    case BACKUP_RESTORE_STARTED = 'BACKUP_RESTORE_STARTED';
    case BACKUP_RESTORE_COMPLETED = 'BACKUP_RESTORE_COMPLETED';
    case BACKUP_RESTORE_FAILED = 'BACKUP_RESTORE_FAILED';
}
